[project]
name = "lidar_tools"
version="0.1.0"
authors = [
  { name = "Scott Henderson", email = "scottyh@uw.edu" },
  { name = "David Shean", email = "dshean@uw.edu" },
  { name = "Shashank Bhushan", email = "shashank.bhushan@nasa.gov" },
  { name = "Karthik Venkataramani", email = "vkarthik@uw.edu" },
]
description = "Centralized airborne lidar processing workflows to generate standard products"
readme = "README.md"
license.file = "LICENSE"
requires-python = ">=3.10"
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  #Not recommended, install via conda-forge instead
  #"PDAL>=3.4.5,<4",
  "cyclopts>=3.9.0,<4",
  "rasterio>=1.4.3,<2",
  "scipy>=1.15.1,<2",
  "geopandas>=1.0.1,<2",
  "requests>=2.32.3,<3",
  "gdal",
  #"python-pdal>=3.5.4,<4.0.0",
  "pdal",
  "rioxarray>=0.19.0,<0.20.0",
  "planetary-computer",
  "odc-stac",
  "pystac-client"

]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project.optional-dependencies]
dev = [
  "ipykernel>=6.29.5,<7",
  "pytest >=6",
]

[project.scripts]
pdal_pipeline = "lidar_tools.cli:app"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.environments]
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.feature.dev.tasks]
test = "pytest"
# pdal_pipeline create-dsm --extent-geojson notebooks/CO_LiDAR_test_area_final.geojson --source-wkt notebooks/SRS_CRS.wkt --target-wkt notebooks/UTM_13N_WGS84_G2139_3D.wkt --output-prefix /tmp/dem
test-create-dsm = "pdal_pipeline create-dsm --source-wkt notebooks/SRS_CRS.wkt notebooks/CO_LiDAR_test_area_final.geojson notebooks/UTM_13N_WGS84_G2139_3D.wkt /tmp/dem"

[tool.pixi.dependencies]
cyclopts = "*"
geopandas = "*"
requests = "*"
scipy = "*"
pystac-client = "*"
gdal = "*"
#python-pdal = "*"
pdal = "*"
rioxarray = "*"
planetary-computer = "*"
odc-stac = "*"

[tool.pixi.pypi-dependencies]
lidar_tools = { path = ".", editable = false }

[tool.pixi.feature.dev.dependencies]
gdal = ">=3.10.1,<4"
pytest = "*"

[tool.pixi.feature.dev.pypi-dependencies]
lidar_tools = { path = ".", editable = true }
