name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: dev
          manifest-path: pyproject.toml
          cache: false
          locked: false
          #cache-write:
          #  ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run Pytest
        run: |
          pixi run test
